/**
 * REAL BUCHAREST, LAID UNDER THE GENERATED CITY.
 *
 * `src/content/bucharest.json` holds curated OpenStreetMap data for the centre
 * of the city — 1,100 building footprints with storey counts, 2,708 classified
 * street centrelines, 183 tram ways, 108 parks and 9 squares — already
 * projected to metres with +X east, +Z south and the origin on Piața
 * Universității. © OpenStreetMap contributors, ODbL 1.0.
 *
 * This module turns that survey into the game's own terms: a road graph, a
 * street-wall of oriented plots, green space, and an occupancy mask that the
 * rest of the city generator reads to know where the real city already is.
 * NO GEOMETRY IS IMPORTED. Every triangle is still generated by the game's
 * grammar; the data supplies layout, rhythm, orientation and height.
 *
 * ==================================================================
 * THE SCALE DECISION — read this before changing OSM_FIT
 * ==================================================================
 *
 * The OSM extent is about 3.7 km east-west by 4.6 km north-south. The game
 * world is `WorldScale.gridBlocks * blockSize` = 26 x 92 m = 2,392 m square.
 * The data does not fit, and the three squares the brief names are the reason:
 *
 *     Piața Victoriei      (-1300, -1845)      real metres from Universitate
 *     Piața Universității  (   -11,   -28)
 *     Piața Unirii         (     0,   870)
 *
 * Victoriei to the far side of Bulevardul Unirii is 2,919 m of north-south
 * alone, against a 2,392 m map. There is no offset that fits them at 1:1, so
 * the only honest choices are to drop one of the named squares or to compress.
 * WE COMPRESS, AND HERE IS EXACTLY BY HOW MUCH:
 *
 *     scale 0.60 — positions and building footprints only.
 *
 * Everything a human is measured against stays at true size: storey heights,
 * lane widths, pavements, doors, cars, lamp posts, the player. Only the map is
 * compressed, which is what every open-world game does with a real city (Los
 * Santos is roughly a tenth of Los Angeles). The consequence is that a block is
 * shorter than its real counterpart and streets are relatively wider — which is
 * the correct trade for a game you drive through.
 *
 * The offset is then forced, not chosen: it puts Piața Universității exactly on
 * the game's authored hero crossroads at (-92, 0). That single alignment buys:
 *
 *   - Bulevardul Magheru / Bălcescu / Brătianu becomes the authored N–S
 *     monumental axis (grid column 12, x = -92),
 *   - Bulevardul Regina Elisabeta / Carol I becomes the authored E–W axis
 *     (grid row 13, z = 0) to within 30 m along its whole run,
 *   - Casa Constructorilor — the story's tower — ends up standing on Piața
 *     Universității, the square Romanian protest actually happens in,
 *   - Piața Victoriei lands at (-896, -1117), the north-west approach, and
 *     Piața Unirii at (-80, 530), both inside the map with margin.
 *
 * 859 of the 1,100 curated footprints and 128 km of real street fall inside the
 * map at this fit.
 *
 * The authored landmarks do NOT move. Where the survey and the story disagree
 * the story wins: real footprints, roads and parks are suppressed inside the
 * landmark voids and the plaza decks (`reserved` below), so Palatul
 * Parlamentului still closes the axis and the broadcast plaza is still there.
 *
 * Buildings are additionally grown about their own centroids by
 * `footprintGrow`, so a real 15 m frontage arrives as 12 m rather than 9.4 m.
 * Compressing positions without compensating the plots would have produced a
 * city of tall thin slivers with gaps between them; the growth is clamped per
 * building against the carriageway mask so nothing grows into a street.
 */

import bucharestJson from '../../content/bucharest.json?raw';
import { WorldScale } from '../../artDirection';
import type { Rng } from '../../core/rng';
import { signedArea, type Vec2 } from './builders';
import { AXIS_X, AXIS_Z } from './districts';

const { blockSize, gridBlocks } = WorldScale;

/** Half the world edge, in metres. */
export const WORLD_HALF = (gridBlocks * blockSize) / 2;

/* ------------------------------------------------------------------ */
/* The fit                                                             */
/* ------------------------------------------------------------------ */

export const OSM_FIT = {
  /** Uniform compression of the survey. See the header. */
  scale: 0.6,
  /** Chosen so Piața Universității lands on the authored crossroads (-92, 0). */
  offsetX: -92 + 11.2 * 0.6,
  offsetZ: 28.21 * 0.6,
  /** Footprints are grown about their centroid to keep human proportions. */
  footprintGrow: 1.18,
} as const;

export function toWorldX(x: number): number {
  return x * OSM_FIT.scale + OSM_FIT.offsetX;
}
export function toWorldZ(z: number): number {
  return z * OSM_FIT.scale + OSM_FIT.offsetZ;
}

/* ------------------------------------------------------------------ */
/* Street classification                                               */
/* ------------------------------------------------------------------ */

export type RoadClass = 'primary' | 'secondary' | 'tertiary' | 'residential' | 'pedestrian';
export type StreetRank = 0 | 1 | 2;

interface ClassSpec {
  /** Carriageway width in TRUE metres — never scaled. */
  carriage: number;
  /** Footway width either side. */
  walk: number;
  rank: StreetRank;
  lampPitch: number;
  treePitch: number;
}

/*
 * Widths are TRUE metres, deliberately at the low end of what Bucharest
 * actually has. The map is compressed to 60% but a lane is not, so the street
 * network eats proportionally more of the ground than it does in life: measured
 * over the centre, carriageway alone was covering a third of the map and the
 * blocks left over could not carry a continuous street wall. Trimming to a
 * 3 m lane and a narrower footway is the smallest correction that gives the
 * blocks their land back, and at 3 m the streets still drive wide.
 */
const CLASS: Record<RoadClass, ClassSpec> = {
  primary: { carriage: 16, walk: 5.0, rank: 2, lampPitch: 30, treePitch: 21 },
  secondary: { carriage: 12, walk: 4.0, rank: 1, lampPitch: 36, treePitch: 25 },
  tertiary: { carriage: 9.5, walk: 3.4, rank: 1, lampPitch: 44, treePitch: 30 },
  residential: { carriage: 7, walk: 2.6, rank: 0, lampPitch: 66, treePitch: 46 },
  pedestrian: { carriage: 0, walk: 8.0, rank: 0, lampPitch: 34, treePitch: 18 },
};

/**
 * The handful of streets a Bucharest local reads as GRAND. OSM's `highway`
 * classes cannot express this: Calea Victoriei is tagged the same "secondary"
 * as a hundred ordinary streets, and Bulevardul Unirii is the widest road in
 * the country. Widths in true metres, applied to the carriageway.
 */
const GRAND: Array<[RegExp, number]> = [
  [/^Bulevardul Unirii/, 28],
  [/^Bulevardul General Gheorghe Magheru/, 22],
  [/^Bulevardul Nicolae Bălcescu/, 22],
  [/^Bulevardul Ion Constantin Brătianu/, 22],
  [/^Bulevardul Regina Elisabeta/, 20],
  [/^Bulevardul Carol I/, 19],
  [/^Bulevardul Lascăr Catargiu/, 20],
  [/^Bulevardul Dacia/, 19],
  [/^Bulevardul Libertății/, 26],
  [/^Bulevardul Dimitrie Cantemir/, 22],
  [/^Șoseaua Ștefan cel Mare/, 20],
  [/^Șoseaua Nicolae Titulescu/, 20],
  [/^Splaiul Independenței/, 19],
  [/^Splaiul Unirii/, 19],
  [/^Calea Victoriei/, 11],
  [/^Calea Moșilor/, 13],
  [/^Piața Unirii/, 20],
];

/* ------------------------------------------------------------------ */
/* Public shapes                                                       */
/* ------------------------------------------------------------------ */

export interface OsmNode {
  x: number;
  z: number;
  /** Highest rank of any street through this node. */
  rank: StreetRank;
  /** Half-width of the largest carriageway here — the junction patch radius. */
  patch: number;
  edges: number[];
}

export interface OsmEdge {
  a: number;
  b: number;
  cls: RoadClass;
  name: string | null;
  /** True metres. */
  width: number;
  walk: number;
  rank: StreetRank;
  /** Lanes per direction. */
  lanes: number;
  oneway: boolean;
  tram: boolean;
  length: number;
}

export interface OsmFootprint {
  ring: Vec2[];
  /** Oriented bounding box of the ring — the site the grammar is given. */
  cx: number;
  cz: number;
  w: number;
  d: number;
  rot: number;
  /** Unit vector from the plot centre toward the street it fronts. */
  fx: number;
  fz: number;
  levels: number;
  name: string | null;
  kind: string;
  area: number;
}

export interface OsmArea {
  ring: Vec2[];
  name: string | null;
}

export interface OsmSquare {
  name: string;
  x: number;
  z: number;
  radius: number;
}

export interface Rect {
  x0: number;
  z0: number;
  x1: number;
  z1: number;
}

/* ------------------------------------------------------------------ */
/* Occupancy masks                                                     */
/* ------------------------------------------------------------------ */

/** Fine mask cell size, metres. */
const CELL = 2;
/** Coverage mask cell size, metres. */
const COVER_CELL = 16;
/** How far from a real street the survey is considered to describe the city. */
const COVER_REACH = 78;

export const Cell = {
  road: 1,
  walk: 2,
  built: 4,
  green: 8,
  reserved: 16,
  square: 32,
  /** Within reach of a real boulevard — see CitySystem.district(). */
  major: 64,
} as const;

export class OccupancyMask {
  readonly n: number;
  readonly data: Uint8Array;
  private readonly cell: number;

  constructor(cell: number) {
    this.cell = cell;
    this.n = Math.ceil((WORLD_HALF * 2) / cell) + 2;
    this.data = new Uint8Array(this.n * this.n);
  }

  private ix(x: number): number {
    return Math.floor((x + WORLD_HALF) / this.cell) + 1;
  }

  at(x: number, z: number): number {
    const i = this.ix(x);
    const j = this.ix(z);
    if (i < 0 || j < 0 || i >= this.n || j >= this.n) return 0;
    return this.data[j * this.n + i];
  }

  has(x: number, z: number, bit: number): boolean {
    return (this.at(x, z) & bit) !== 0;
  }

  /** Stamp a capsule of the given width along a segment. */
  stampSegment(
    x0: number, z0: number, x1: number, z1: number, width: number, bit: number,
  ): void {
    const hw = width / 2;
    const i0 = this.ix(Math.min(x0, x1) - hw);
    const i1 = this.ix(Math.max(x0, x1) + hw);
    const j0 = this.ix(Math.min(z0, z1) - hw);
    const j1 = this.ix(Math.max(z0, z1) + hw);
    const dx = x1 - x0;
    const dz = z1 - z0;
    const len2 = dx * dx + dz * dz || 1;
    const hw2 = hw * hw;
    for (let j = Math.max(0, j0); j <= Math.min(this.n - 1, j1); j++) {
      const pz = (j - 1) * this.cell - WORLD_HALF + this.cell * 0.5;
      for (let i = Math.max(0, i0); i <= Math.min(this.n - 1, i1); i++) {
        const px = (i - 1) * this.cell - WORLD_HALF + this.cell * 0.5;
        let t = ((px - x0) * dx + (pz - z0) * dz) / len2;
        t = t < 0 ? 0 : t > 1 ? 1 : t;
        const ex = px - (x0 + dx * t);
        const ez = pz - (z0 + dz * t);
        if (ex * ex + ez * ez <= hw2) this.data[j * this.n + i] |= bit;
      }
    }
  }

  stampRect(cx: number, cz: number, w: number, d: number, rot: number, bit: number): void {
    const cs = Math.cos(rot);
    const sn = Math.sin(rot);
    const r = Math.hypot(w, d) / 2;
    const i0 = this.ix(cx - r);
    const i1 = this.ix(cx + r);
    const j0 = this.ix(cz - r);
    const j1 = this.ix(cz + r);
    const hw = w / 2;
    const hd = d / 2;
    for (let j = Math.max(0, j0); j <= Math.min(this.n - 1, j1); j++) {
      const pz = (j - 1) * this.cell - WORLD_HALF + this.cell * 0.5;
      for (let i = Math.max(0, i0); i <= Math.min(this.n - 1, i1); i++) {
        const px = (i - 1) * this.cell - WORLD_HALF + this.cell * 0.5;
        const ox = px - cx;
        const oz = pz - cz;
        // Inverse of rectFootprint's mapping.
        const lx = ox * cs - oz * sn;
        const lz = ox * sn + oz * cs;
        if (Math.abs(lx) <= hw && Math.abs(lz) <= hd) this.data[j * this.n + i] |= bit;
      }
    }
  }

  stampDisc(cx: number, cz: number, r: number, bit: number): void {
    const i0 = Math.max(0, this.ix(cx - r));
    const i1 = Math.min(this.n - 1, this.ix(cx + r));
    const j0 = Math.max(0, this.ix(cz - r));
    const j1 = Math.min(this.n - 1, this.ix(cz + r));
    const r2 = r * r;
    for (let j = j0; j <= j1; j++) {
      const pz = (j - 1) * this.cell - WORLD_HALF + this.cell * 0.5;
      for (let i = i0; i <= i1; i++) {
        const px = (i - 1) * this.cell - WORLD_HALF + this.cell * 0.5;
        if ((px - cx) ** 2 + (pz - cz) ** 2 <= r2) this.data[j * this.n + i] |= bit;
      }
    }
  }

  stampPolygon(ring: ReadonlyArray<Vec2>, bit: number): void {
    let x0 = Infinity; let x1 = -Infinity; let z0 = Infinity; let z1 = -Infinity;
    for (const v of ring) {
      if (v.x < x0) x0 = v.x;
      if (v.x > x1) x1 = v.x;
      if (v.z < z0) z0 = v.z;
      if (v.z > z1) z1 = v.z;
    }
    const i0 = Math.max(0, this.ix(x0));
    const i1 = Math.min(this.n - 1, this.ix(x1));
    const j0 = Math.max(0, this.ix(z0));
    const j1 = Math.min(this.n - 1, this.ix(z1));
    for (let j = j0; j <= j1; j++) {
      const pz = (j - 1) * this.cell - WORLD_HALF + this.cell * 0.5;
      for (let i = i0; i <= i1; i++) {
        const px = (i - 1) * this.cell - WORLD_HALF + this.cell * 0.5;
        if (pointInRing(ring, px, pz)) this.data[j * this.n + i] |= bit;
      }
    }
  }

  /** True when ANY cell of the oriented rect carries one of `bits`. */
  rectHits(cx: number, cz: number, w: number, d: number, rot: number, bits: number): boolean {
    const cs = Math.cos(rot);
    const sn = Math.sin(rot);
    const steps = (v: number): number => Math.max(1, Math.round(v / this.cell));
    const nu = steps(w);
    const nv = steps(d);
    for (let u = 0; u <= nu; u++) {
      const lx = (u / nu - 0.5) * w;
      for (let v = 0; v <= nv; v++) {
        const lz = (v / nv - 0.5) * d;
        const px = cx + lx * cs + lz * sn;
        const pz = cz - lx * sn + lz * cs;
        if ((this.at(px, pz) & bits) !== 0) return true;
      }
    }
    return false;
  }
}

export function pointInRing(ring: ReadonlyArray<Vec2>, x: number, z: number): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const a = ring[i];
    const b = ring[j];
    if ((a.z > z) !== (b.z > z)
      && x < ((b.x - a.x) * (z - a.z)) / (b.z - a.z) + a.x) inside = !inside;
  }
  return inside;
}

/* ------------------------------------------------------------------ */
/* The imported city                                                   */
/* ------------------------------------------------------------------ */

export interface OsmCityOptions {
  /** Ground the story owns — landmark voids and plaza decks. */
  reserved: Rect[];
  rng: Rng;
}

export class OsmCity {
  readonly nodes: OsmNode[] = [];
  readonly edges: OsmEdge[] = [];
  readonly footprints: OsmFootprint[] = [];
  readonly parks: OsmArea[] = [];
  readonly squares: OsmSquare[] = [];
  readonly trams: Vec2[][] = [];
  /** Named buildings worth putting on the map. */
  readonly places: Array<{ name: string; x: number; z: number; radius: number; kind: string }> = [];

  readonly mask = new OccupancyMask(CELL);
  readonly cover = new OccupancyMask(COVER_CELL);

  /** Real building centroids, hashed, for sampling the local storey count. */
  private levelHash = new Map<number, Array<{ x: number; z: number; levels: number }>>();
  private static readonly LEVEL_CELL = 120;

  stats = {
    ways: 0, nodes: 0, edges: 0, footprints: 0, parks: 0, dropped: 0, roadKm: 0, generalised: 0,
  };

  /** True where the survey describes the city, so the grid must stand aside. */
  covered(x: number, z: number): boolean {
    return this.cover.has(x, z, Cell.road);
  }

  isCarriageway(x: number, z: number): boolean {
    return this.mask.has(x, z, Cell.road);
  }

  /**
   * Storey count of the real buildings around a point, for infill that has to
   * agree with its neighbours. Falls back to 0 when nothing is near.
   */
  levelsNear(x: number, z: number): number {
    const c = OsmCity.LEVEL_CELL;
    const i = Math.floor(x / c);
    const j = Math.floor(z / c);
    let sum = 0;
    let n = 0;
    let best = Infinity;
    let bestLv = 0;
    for (let di = -1; di <= 1; di++) {
      for (let dj = -1; dj <= 1; dj++) {
        const list = this.levelHash.get((i + di) * 100003 + (j + dj));
        if (!list) continue;
        for (const e of list) {
          const d2 = (e.x - x) ** 2 + (e.z - z) ** 2;
          if (d2 > 200 * 200) continue;
          sum += e.levels;
          n++;
          if (d2 < best) { best = d2; bestLv = e.levels; }
        }
      }
    }
    if (!n) return 0;
    // Weighted toward the nearest neighbour so a lone tower does not lift a
    // whole street, but a street of P+4 keeps its infill at P+4.
    return (sum / n) * 0.45 + bestLv * 0.55;
  }

  addLevelSample(x: number, z: number, levels: number): void {
    const c = OsmCity.LEVEL_CELL;
    const key = Math.floor(x / c) * 100003 + Math.floor(z / c);
    let list = this.levelHash.get(key);
    if (!list) this.levelHash.set(key, (list = []));
    list.push({ x, z, levels });
  }
}

/* ------------------------------------------------------------------ */
/* Raw document                                                        */
/* ------------------------------------------------------------------ */

interface RawRoad {
  name?: string | null;
  cls: string;
  lanes?: number | null;
  oneway?: boolean;
  path: Array<[number, number]>;
}
interface RawBuilding {
  name?: string | null;
  kind?: string;
  levels: number;
  ring: Array<[number, number]>;
}
interface RawArea { name?: string | null; ring: Array<[number, number]> }
interface RawSquare { name: string; x?: number; z?: number; ring?: Array<[number, number]> }
interface RawDoc {
  roads: RawRoad[];
  buildings: RawBuilding[];
  parks: RawArea[];
  squares: RawSquare[];
  trams: Array<{ path: Array<[number, number]> }>;
}

let cachedDoc: RawDoc | null = null;
function doc(): RawDoc {
  if (!cachedDoc) cachedDoc = JSON.parse(bucharestJson) as RawDoc;
  return cachedDoc;
}

/* ------------------------------------------------------------------ */
/* Build                                                               */
/* ------------------------------------------------------------------ */

/** Margin outside the map edge that geometry may still be built into. */
const EDGE = WORLD_HALF - 6;

function inWorld(x: number, z: number): boolean {
  return x > -EDGE && x < EDGE && z > -EDGE && z < EDGE;
}

export function buildOsmCity(opt: OsmCityOptions): OsmCity {
  const city = new OsmCity();
  const d = doc();

  buildNetwork(city, d.roads);
  stampReserved(city, opt.reserved);
  stampAuthoredAxes(city);
  buildGreen(city, d.parks, d.squares);
  squaresFromRoads(city, d.roads);
  buildFootprints(city, d.buildings);
  buildTrams(city, d.trams);

  return city;
}

/**
 * The two authored boulevards are laid by the grid, not by the survey, so the
 * survey has to be told they are there — otherwise a real footprint lands in
 * the middle of the 42 m carriageway Casa Constructorilor's forecourt opens on.
 */
function stampAuthoredAxes(city: OsmCity): void {
  const w = 42;
  const walk = 9.5;
  const span = WORLD_HALF * 2;
  city.mask.stampRect(AXIS_X, 0, w, span, 0, Cell.road);
  city.mask.stampRect(0, AXIS_Z, span, w, 0, Cell.road);
  city.mask.stampRect(AXIS_X, 0, w + walk * 2, span, 0, Cell.walk);
  city.mask.stampRect(0, AXIS_Z, span, w + walk * 2, 0, Cell.walk);
}

/* ---------------- road network ---------------- */

function classOf(cls: string): RoadClass {
  switch (cls) {
    case 'primary': case 'secondary': case 'tertiary':
    case 'residential': case 'pedestrian':
      return cls;
    default:
      return 'residential';
  }
}

function widthOf(name: string | null, cls: RoadClass, lanes: number | null): number {
  const spec = CLASS[cls];
  if (name) {
    for (const [re, w] of GRAND) if (re.test(name)) return w;
  }
  if (cls === 'pedestrian') return 0;
  if (lanes && lanes > 0) {
    return Math.max(spec.carriage * 0.8, Math.min(spec.carriage * 1.6, lanes * 3.0 + 1.2));
  }
  return spec.carriage;
}

/**
 * The two authored boulevards the story is staged on. Real ways that run along
 * them are dropped rather than drawn twice: the grid still lays these two, at
 * their authored 42 m, because Casa Constructorilor's forecourt, the Dacia's
 * kerbside slot and the Parliament axis are all measured against them.
 */
const AXIS_KEEPOUT = 15;

function onAuthoredAxis(
  ax: number, az: number, bx: number, bz: number,
): boolean {
  const mx = (ax + bx) / 2;
  const mz = (az + bz) / 2;
  const dx = bx - ax;
  const dz = bz - az;
  const len = Math.hypot(dx, dz) || 1;
  // Near-parallel and close to the centreline.
  if (Math.abs(mx - AXIS_X) < AXIS_KEEPOUT && Math.abs(dz / len) > 0.85) return true;
  if (Math.abs(mz - AXIS_Z) < AXIS_KEEPOUT && Math.abs(dx / len) > 0.85) return true;
  return false;
}

function buildNetwork(city: OsmCity, roads: RawRoad[]): void {
  /* Junction detection happens in SOURCE coordinates: OSM ways share the exact
   * node coordinates where they meet, and rounding after the transform would
   * merge distinct nodes on the compressed map. */
  const shared = new Map<string, number>();
  const key = (p: [number, number]): string => `${p[0].toFixed(1)},${p[1].toFixed(1)}`;
  for (const r of roads) {
    for (const p of r.path) shared.set(key(p), (shared.get(key(p)) ?? 0) + 1);
  }

  const nodeAt = new Map<string, number>();
  const nodeKey = (x: number, z: number): string =>
    `${Math.round(x / 0.6)},${Math.round(z / 0.6)}`;

  const nodeId = (x: number, z: number, rank: StreetRank, patch: number): number => {
    const k = nodeKey(x, z);
    const found = nodeAt.get(k);
    if (found !== undefined) {
      const n = city.nodes[found];
      if (rank > n.rank) n.rank = rank;
      if (patch > n.patch) n.patch = patch;
      return found;
    }
    const id = city.nodes.length;
    city.nodes.push({ x, z, rank, patch, edges: [] });
    nodeAt.set(k, id);
    return id;
  };

  /*
   * CARTOGRAPHIC GENERALISATION — the pass that makes a compressed map read.
   *
   * A lane stays 3 m wide while the map shrinks to 60%, so the street network
   * eats proportionally more ground than it does in life. Imported literally,
   * central Bucharest came out as a third carriageway by area with the blocks
   * between it too thin to carry a street wall — more road than city.
   *
   * The fix is the one a cartographer uses when a map is reduced: drop the
   * streets that no longer earn their space. Ways are laid in order of
   * importance and a minor one is skipped where its corridor is ALREADY
   * tarmac — the parallel service road beside a boulevard, the second half of
   * a dual carriageway, the inner ring of a roundabout, the parking aisle
   * behind a block. Nothing that carries the shape of the city is lost, and
   * the blocks get their land back.
   */
  const RANK_ORDER: RoadClass[] = ['primary', 'secondary', 'tertiary', 'residential', 'pedestrian'];
  const ordered = roads.slice().sort(
    (a, b) => RANK_ORDER.indexOf(classOf(a.cls)) - RANK_ORDER.indexOf(classOf(b.cls)),
  );

  const alreadyPaved = (a: Vec2, b: Vec2): boolean => {
    let on = 0;
    const n = 5;
    for (let i = 0; i <= n; i++) {
      const t = i / n;
      if (city.mask.has(a.x + (b.x - a.x) * t, a.z + (b.z - a.z) * t, Cell.road)) on++;
    }
    return on > n * 0.6;
  };

  for (const r of ordered) {
    const cls = classOf(r.cls);
    const name = r.name ?? null;
    const width = widthOf(name, cls, r.lanes ?? null);
    const spec = CLASS[cls];
    const walk = spec.walk;
    const lanes = Math.max(1, Math.round((r.lanes ?? 2) / (r.oneway ? 1 : 2)));

    // Transform, remembering which vertices are shared junctions.
    const pts: Vec2[] = [];
    const forced: boolean[] = [];
    for (const p of r.path) {
      pts.push({ x: toWorldX(p[0]), z: toWorldZ(p[1]) });
      forced.push((shared.get(key(p)) ?? 0) > 1);
    }

    // Split into runs that lie inside the map.
    let run: Vec2[] = [];
    let runForced: boolean[] = [];
    const flush = (): void => {
      if (run.length >= 2) emitWay(run, runForced);
      run = [];
      runForced = [];
    };
    for (let i = 0; i < pts.length; i++) {
      if (inWorld(pts[i].x, pts[i].z)) {
        run.push(pts[i]);
        runForced.push(forced[i]);
      } else flush();
    }
    flush();
    city.stats.ways++;

    function emitWay(way: Vec2[], force: boolean[]): void {
      const keep = simplify(way, force, 1.6, 9, 56);
      for (let i = 0; i + 1 < keep.length; i++) {
        const a = way[keep[i]];
        const b = way[keep[i + 1]];
        const len = Math.hypot(b.x - a.x, b.z - a.z);
        if (len < 0.5) continue;
        if (onAuthoredAxis(a.x, a.z, b.x, b.z)) continue;
        if (spec.rank === 0 && alreadyPaved(a, b)) { city.stats.generalised++; continue; }
        const na = nodeId(a.x, a.z, spec.rank, width / 2);
        const nb = nodeId(b.x, b.z, spec.rank, width / 2);
        if (na === nb) continue;
        const id = city.edges.length;
        city.edges.push({
          a: na, b: nb, cls, name, width, walk, rank: spec.rank,
          lanes, oneway: !!r.oneway, tram: false, length: len,
        });
        city.nodes[na].edges.push(id);
        city.nodes[nb].edges.push(id);
        city.stats.roadKm += len / 1000;
        // Claim the corridor immediately so the next minor way sees it.
        if (width > 0) city.mask.stampSegment(a.x, a.z, b.x, b.z, width, Cell.road);
      }
    }
  }

  // Footway corridors and coverage. Carriageways were stamped as they were
  // laid, because the generalisation pass above reads them back.
  for (const e of city.edges) {
    const a = city.nodes[e.a];
    const b = city.nodes[e.b];
    city.mask.stampSegment(a.x, a.z, b.x, b.z, e.width + e.walk * 2, Cell.walk);
    if (e.rank >= 1) city.mask.stampSegment(a.x, a.z, b.x, b.z, e.width + 130, Cell.major);
    city.cover.stampSegment(a.x, a.z, b.x, b.z, e.width + COVER_REACH * 2, Cell.road);
  }

  city.stats.nodes = city.nodes.length;
  city.stats.edges = city.edges.length;
}

/**
 * Douglas–Peucker, then a spacing pass.
 *
 * The graph and the ribbons share one vertex list, so the tolerance has to
 * serve both: too coarse and Calea Victoriei's curve becomes a dogleg, too fine
 * and A* is walking ten thousand nodes. Junction vertices are always kept —
 * they are what makes the two ways meet in the graph at all.
 */
function simplify(
  pts: ReadonlyArray<Vec2>,
  forced: ReadonlyArray<boolean>,
  tol: number,
  minSpacing: number,
  maxSpacing: number,
): number[] {
  const n = pts.length;
  const keep = new Uint8Array(n);
  keep[0] = 1;
  keep[n - 1] = 1;
  for (let i = 0; i < n; i++) if (forced[i]) keep[i] = 1;

  // DP between consecutive forced anchors.
  const anchors: number[] = [];
  for (let i = 0; i < n; i++) if (keep[i]) anchors.push(i);
  for (let k = 0; k + 1 < anchors.length; k++) {
    dp(pts, anchors[k], anchors[k + 1], tol, keep);
  }

  // Spacing: drop non-forced vertices that crowd, insert nothing (a long
  // straight run needs no extra nodes; the ribbon is straight anyway).
  const out: number[] = [];
  let lastX = 0;
  let lastZ = 0;
  for (let i = 0; i < n; i++) {
    if (!keep[i]) continue;
    if (out.length && !forced[i] && i !== n - 1) {
      if (Math.hypot(pts[i].x - lastX, pts[i].z - lastZ) < minSpacing) continue;
    }
    out.push(i);
    lastX = pts[i].x;
    lastZ = pts[i].z;
  }
  void maxSpacing;
  return out;
}

function dp(
  pts: ReadonlyArray<Vec2>, i0: number, i1: number, tol: number, keep: Uint8Array,
): void {
  if (i1 - i0 < 2) return;
  const a = pts[i0];
  const b = pts[i1];
  const dx = b.x - a.x;
  const dz = b.z - a.z;
  const len = Math.hypot(dx, dz) || 1;
  let worst = 0;
  let at = -1;
  for (let i = i0 + 1; i < i1; i++) {
    const p = pts[i];
    const dist = Math.abs((p.x - a.x) * dz - (p.z - a.z) * dx) / len;
    if (dist > worst) { worst = dist; at = i; }
  }
  if (worst <= tol || at < 0) return;
  keep[at] = 1;
  dp(pts, i0, at, tol, keep);
  dp(pts, at, i1, tol, keep);
}

/* ---------------- reserved ground ---------------- */

function stampReserved(city: OsmCity, rects: Rect[]): void {
  for (const r of rects) {
    city.mask.stampRect(
      (r.x0 + r.x1) / 2, (r.z0 + r.z1) / 2,
      r.x1 - r.x0, r.z1 - r.z0, 0, Cell.reserved,
    );
  }
}

function isReserved(city: OsmCity, x: number, z: number): boolean {
  return city.mask.has(x, z, Cell.reserved);
}

/* ---------------- parks and squares ---------------- */

function buildGreen(city: OsmCity, parks: RawArea[], squares: RawSquare[]): void {
  for (const p of parks) {
    const ring = toRing(p.ring);
    if (ring.length < 3) continue;
    const b = ringBounds(ring);
    if (!overlapsWorld(b)) continue;
    // A park cut in half by the map edge is worse than no park.
    const clipped = clipRingToWorld(ring);
    if (clipped.length < 3) continue;
    if (Math.abs(signedArea(clipped)) < 340) continue;
    city.parks.push({ ring: clipped, name: p.name ?? null });
    city.mask.stampPolygon(clipped, Cell.green);
  }
  city.stats.parks = city.parks.length;

  for (const s of squares) {
    let x: number;
    let z: number;
    if (s.ring && s.ring.length) {
      const ring = toRing(s.ring);
      const b = ringBounds(ring);
      x = (b.x0 + b.x1) / 2;
      z = (b.z0 + b.z1) / 2;
    } else if (s.x !== undefined && s.z !== undefined) {
      x = toWorldX(s.x);
      z = toWorldZ(s.z);
    } else continue;
    if (!inWorld(x, z)) continue;
    const radius = 38;
    city.squares.push({ name: s.name, x, z, radius });
    city.mask.stampDisc(x, z, radius, Cell.square);
  }

}

/**
 * The squares that matter most — Victoriei, Universității, Romană, Revoluției —
 * are NOT areas in the survey. OSM maps a Bucharest square as the bundle of
 * carriageways named after it, so they arrive as roads and would have been
 * paved as ordinary tarmac. Recovering them is the whole point of the import,
 * so every road whose name begins "Piața" is collapsed to its centroid and
 * given a stone deck sized to the spread of its own carriageways.
 */
function squaresFromRoads(city: OsmCity, roads: RawRoad[]): void {
  const groups = new Map<string, Vec2[]>();
  for (const r of roads) {
    if (!r.name || !/^Piața /.test(r.name)) continue;
    let list = groups.get(r.name);
    if (!list) groups.set(r.name, (list = []));
    for (const p of r.path) list.push({ x: toWorldX(p[0]), z: toWorldZ(p[1]) });
  }
  for (const [name, pts] of groups) {
    const c = centroid(pts);
    if (!inWorld(c.x, c.z)) continue;
    if (isReserved(city, c.x, c.z)) continue;
    if (city.squares.some((s) => Math.hypot(s.x - c.x, s.z - c.z) < 70)) continue;
    // Radius from the spread of the square's own carriageways, but never so
    // large that it swallows the blocks around it.
    let rms = 0;
    for (const p of pts) rms += (p.x - c.x) ** 2 + (p.z - c.z) ** 2;
    // Capped hard. A square is a room in the city, not a field: at 66 m the
    // deck swallowed the blocks around Piața Universității and pushed its own
    // frontage back until the square had no walls at all.
    const radius = Math.max(22, Math.min(44, Math.sqrt(rms / pts.length) * 0.7));
    city.squares.push({ name, x: c.x, z: c.z, radius });
    city.mask.stampDisc(c.x, c.z, radius, Cell.square);
  }
}

/* ---------------- footprints ---------------- */

function buildFootprints(city: OsmCity, buildings: RawBuilding[]): void {
  for (const b of buildings) {
    let ring = toRing(b.ring);
    if (ring.length < 3) continue;
    const bounds = ringBounds(ring);
    if (!overlapsWorld(bounds)) continue;

    // Grow about the centroid to recover human proportions after the map
    // compression, backing off in steps if the growth would eat the street.
    const c = centroid(ring);
    let grown = ring;
    for (const g of [OSM_FIT.footprintGrow, 1.15, 1.0]) {
      grown = g === 1 ? ring : ring.map((v) => ({
        x: c.x + (v.x - c.x) * g,
        z: c.z + (v.z - c.z) * g,
      }));
      if (!ringHitsRoad(city, grown)) break;
    }
    ring = grown;

    const area = Math.abs(signedArea(ring));
    if (area < 34) { city.stats.dropped++; continue; }

    const cc = centroid(ring);
    if (!inWorld(cc.x, cc.z)) { city.stats.dropped++; continue; }
    if (isReserved(city, cc.x, cc.z)) { city.stats.dropped++; continue; }
    if (city.mask.has(cc.x, cc.z, Cell.road)) { city.stats.dropped++; continue; }

    const box = minAreaRect(ring);
    const face = facingOf(city, cc.x, cc.z, box.rot);

    const fp: OsmFootprint = {
      ring,
      cx: box.cx, cz: box.cz, w: box.w, d: box.d, rot: box.rot,
      fx: face.x, fz: face.z,
      levels: Math.max(1, b.levels),
      name: b.name ?? null,
      kind: b.kind ?? 'yes',
      area,
    };
    city.footprints.push(fp);
    city.mask.stampPolygon(ring, Cell.built);
    city.addLevelSample(cc.x, cc.z, fp.levels);

    if (fp.name && isPlaceName(fp.name, area, fp.kind)) {
      city.places.push({
        name: fp.name, x: cc.x, z: cc.z,
        radius: Math.max(18, Math.sqrt(area) * 0.6),
        kind: fp.kind,
      });
    }
  }
  city.stats.footprints = city.footprints.length;
}

/**
 * Which named buildings deserve a pin on the map.
 *
 * OSM names a great deal that a player would never call a place: block
 * numbers, heating substations, a supermarket unit, "Corp C", "sala de sport".
 * The map is a navigation aid, so the bar is a building someone would give as
 * a direction — a palace, a theatre, a church, a ministry, a hotel — or simply
 * something big enough to be a landmark by mass alone.
 */
const NOT_A_PLACE = /^(bl\.?|bloc|sc\.?|scara|tronson|p\d+$|punct termic|corp\b|cladire|clădire|anexa|anexă|garaj|magazie|depozit|hala|hală|sala\b|parcare)/i;
const IS_A_PLACE = /^(pala|palat|catedral|biseric|teatr|muzeu|hotel|banca|banc[ăa]|universit|colegiu|liceu|academia|ateneu|spital|primăria|ministerul|tribunal|gara |institut|casa |sala palatului|opera)/i;

function isPlaceName(n: string, area: number, kind: string): boolean {
  const t = n.trim();
  if (t.length < 4) return false;
  if (NOT_A_PLACE.test(t)) return false;
  if (IS_A_PLACE.test(t)) return true;
  if (kind === 'church' || kind === 'cathedral' || kind === 'university'
    || kind === 'public' || kind === 'government' || kind === 'hotel') return true;
  // Otherwise it has to earn it by mass.
  return area > 1600;
}

function ringHitsRoad(city: OsmCity, ring: ReadonlyArray<Vec2>): boolean {
  for (const v of ring) if (city.mask.has(v.x, v.z, Cell.road)) return true;
  return false;
}

/**
 * Which way this plot faces. The grammar puts the entrance, the balconies and
 * the shopfront on this side, so getting it wrong turns a street wall inside
 * out. Take the nearest carriageway within reach, otherwise fall back to the
 * long axis of the plot.
 */
function facingOf(city: OsmCity, cx: number, cz: number, rot: number): Vec2 {
  const cs = Math.cos(rot);
  const sn = Math.sin(rot);
  // The two candidate faces are along the OBB's local +/- z axis, i.e. the
  // long-side normals: local +z maps to (sin, cos).
  const cand: Vec2[] = [
    { x: sn, z: cs }, { x: -sn, z: -cs },
    { x: cs, z: -sn }, { x: -cs, z: sn },
  ];
  let best = cand[0];
  let bestD = Infinity;
  for (const c of cand) {
    for (let t = 6; t <= 46; t += 4) {
      if (city.mask.has(cx + c.x * t, cz + c.z * t, Cell.road)) {
        if (t < bestD) { bestD = t; best = c; }
        break;
      }
    }
  }
  return best;
}

/* ---------------- trams ---------------- */

function buildTrams(city: OsmCity, trams: Array<{ path: Array<[number, number]> }>): void {
  for (const t of trams) {
    let run: Vec2[] = [];
    const flush = (): void => {
      if (run.length >= 2) {
        const forced = run.map((_, i) => i === 0 || i === run.length - 1);
        const keep = simplify(run, forced, 1.4, 8, 60);
        city.trams.push(keep.map((i) => run[i]));
      }
      run = [];
    };
    for (const p of t.path) {
      const x = toWorldX(p[0]);
      const z = toWorldZ(p[1]);
      if (inWorld(x, z)) run.push({ x, z });
      else flush();
    }
    flush();
  }
}

/* ------------------------------------------------------------------ */
/* Geometry helpers                                                    */
/* ------------------------------------------------------------------ */

function toRing(raw: Array<[number, number]>): Vec2[] {
  const out: Vec2[] = [];
  for (const p of raw) out.push({ x: toWorldX(p[0]), z: toWorldZ(p[1]) });
  // OSM closes its rings; the builders do not want the duplicate.
  while (out.length > 1) {
    const a = out[0];
    const b = out[out.length - 1];
    if (Math.hypot(a.x - b.x, a.z - b.z) < 0.05) out.pop();
    else break;
  }
  // Normalise to the clockwise-from-above winding the builders assume.
  if (signedArea(out) > 0) out.reverse();
  return out;
}

export function centroid(ring: ReadonlyArray<Vec2>): Vec2 {
  let x = 0;
  let z = 0;
  for (const v of ring) { x += v.x; z += v.z; }
  return { x: x / ring.length, z: z / ring.length };
}

function ringBounds(ring: ReadonlyArray<Vec2>): Rect {
  let x0 = Infinity; let x1 = -Infinity; let z0 = Infinity; let z1 = -Infinity;
  for (const v of ring) {
    if (v.x < x0) x0 = v.x;
    if (v.x > x1) x1 = v.x;
    if (v.z < z0) z0 = v.z;
    if (v.z > z1) z1 = v.z;
  }
  return { x0, z0, x1, z1 };
}

function overlapsWorld(b: Rect): boolean {
  return b.x1 > -EDGE && b.x0 < EDGE && b.z1 > -EDGE && b.z0 < EDGE;
}

/** Sutherland–Hodgman against the map square. */
function clipRingToWorld(ring: ReadonlyArray<Vec2>): Vec2[] {
  let poly = ring.slice();
  const planes: Array<[number, number, number]> = [
    [1, 0, -EDGE], [-1, 0, -EDGE], [0, 1, -EDGE], [0, -1, -EDGE],
  ];
  for (const [nx, nz, off] of planes) {
    const next: Vec2[] = [];
    for (let i = 0; i < poly.length; i++) {
      const a = poly[i];
      const b = poly[(i + 1) % poly.length];
      const da = nx * a.x + nz * a.z + off;
      const db = nx * b.x + nz * b.z + off;
      if (da <= 0) next.push(a);
      if ((da <= 0) !== (db <= 0)) {
        const t = da / (da - db);
        next.push({ x: a.x + (b.x - a.x) * t, z: a.z + (b.z - a.z) * t });
      }
    }
    poly = next;
    if (!poly.length) return poly;
  }
  return poly;
}

/**
 * Minimum-area oriented bounding box, tested against every edge direction.
 * The angle is returned in `rectFootprint`'s convention, so the grammar can be
 * handed `{cx, cz, w, d, rot}` and produce a plot that sits on its real street.
 */
export function minAreaRect(
  ring: ReadonlyArray<Vec2>,
): { cx: number; cz: number; w: number; d: number; rot: number } {
  let best = { cx: 0, cz: 0, w: 1, d: 1, rot: 0, area: Infinity };
  for (let i = 0; i < ring.length; i++) {
    const a = ring[i];
    const b = ring[(i + 1) % ring.length];
    const dx = b.x - a.x;
    const dz = b.z - a.z;
    const len = Math.hypot(dx, dz);
    if (len < 0.2) continue;
    const ex = dx / len;
    const ez = dz / len;
    // local +x = (cos, -sin) -> cos = ex, sin = -ez.  local +z = (sin, cos).
    const fx = -ez;
    const fz = ex;
    let u0 = Infinity; let u1 = -Infinity; let v0 = Infinity; let v1 = -Infinity;
    for (const p of ring) {
      const u = p.x * ex + p.z * ez;
      const v = p.x * fx + p.z * fz;
      if (u < u0) u0 = u;
      if (u > u1) u1 = u;
      if (v < v0) v0 = v;
      if (v > v1) v1 = v;
    }
    const w = u1 - u0;
    const dd = v1 - v0;
    const area = w * dd;
    if (area < best.area) {
      const uc = (u0 + u1) / 2;
      const vc = (v0 + v1) / 2;
      best = {
        cx: ex * uc + fx * vc,
        cz: ez * uc + fz * vc,
        w, d: dd,
        rot: Math.atan2(-ez, ex),
        area,
      };
    }
  }
  return { cx: best.cx, cz: best.cz, w: best.w, d: best.d, rot: best.rot };
}

/** Class spec lookup, for the street builder. */
export function classSpec(cls: RoadClass): ClassSpec {
  return CLASS[cls];
}
